---
output: github_document
title: "pimimport"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

<!-- badges: start -->
<!-- badges: end -->

The `pimimport` package facilitates the importation of 'Excel' XML reports generated by PIMsoft into R environments aswell as tab seperated value documents containing graph data. These reports often present challenges due to inconsistencies in data structure, which pim efficiently addresses, simplifying the data integration process.

## Prerequisites

This package is specifically designed for use with PIMsoft version 1.5.8.2090555 (64-bit) developed by Perimed AB.
It assumes that the XML files are generated using the built-in report function with the following options selected: "Recording info", "Calculations", "Mean perfusion", and "Percent change per ROI".
Furthermore, ROIs must be named "ACH", "SNP", and "ref", and TOIs must include "rest", "ACHmax", and "SNPmax".
Graphdata import assumes that rest timestamp is set using aforementioned software.

## Installation

`pimimport` can be installed directly from GitHub using the `devtools` package. If you do not have `devtools` installed, you can install it using the command `install.packages("devtools")`. Then, install `pimimport` using:

``` r
# install.packages("devtools")
devtools::install_github("Widaeus/pimimport")
```

## Usage

The `pimimport` package includes three primary functions: `xml_to_df`, `tsv_convert` and `folder_to_df`.

`xml_to_df`: This function accepts a URL pointing to an XML file that meets the specified prerequisites and transforms it into a tidy data frame consisting of one row per observation and multiple relevant columns.

`folder_to_df`: This function processes all XML files in a specified folder, applying `xml_to_df` to each file and compiling the results into a single data frame by binding the rows together.

`tsv_convert`: This function takes graph data saved as a tsv file and converts it to a list of raw tsv data for graph presentation aswell as a tibble of relevant variables for usage in analysis.

These functions streamline the process of converting XML reports and graphdata into manageable R data frames, significantly easing the data analysis workflow and grah presentation.
