#' turn tibbles in to single row data
#' @description *Applicable to microvasc research group, Danderyds Sjukhus workflow*. Takes tibbles from "xml_to_tibbles" and generates 4 tibbles of single row data.
#'
#' @param tibbles_list a list of 4 tibbles generated by xml_to_tibbles function.
#'
#' @import dplyr
#' @import tidyr
#' @import purrr
#' @import stringr
#' @import tibble
#' @import lubridate
#' @import xml2
#'
#' @return returns 1 tibble with one singlerow.
#' @export
#'
tibbles_to_singlerow <- function(tibbles_list) {
  # Extracting each tibble from the list
  recinfo_data <- tibbles_list$recinfo_data
  calc_data <- tibbles_list$calc_data
  meanperf_data <- tibbles_list$meanperf_data
  roi_data <- tibbles_list$roi_data

#selecting relevant variables and single row transform # recinfo
recinfo_data <- recinfo_data %>%
  mutate(row_id = c("id", "datetime")) %>%
  pivot_wider(names_from = 2, values_from = 1) %>%
  mutate(datetime = ymd_hms(datetime))

# selecting relevant variable and single row transform # meanperf
meanperf_data <- meanperf_data %>%
  select(
    1,
      matches("rest"),
      matches("[Aa].*max"),
      matches("[Ss].*max")
    ) %>%
  slice(-n()) %>%
  pivot_wider(names_from = 1, values_from = c(2, 3, 4)) %>%
  summarize(across(everything(), ~ .[!is.na(.)][1])) %>%
  rename_with(~ paste0("meanperf_", .), .cols = everything())

#selecting relevant variables and single row transform # calc
calc_data <- calc_data %>%
  filter(str_detect(Calculations, "rest|ACHmax|SNPmax")) %>%
  filter(!str_detect(Calculations, "Entireimg")) %>%
  pivot_wider(names_from = Calculations, values_from = c(2:6)) %>%
  summarize(across(everything(), ~ .[!is.na(.)][1]))

#selecting relevant variables and single row transform # roi
roi_data <- roi_data %>%
  select(Change, rest, ACHmax, SNPmax) %>%
  filter(!str_detect(Change, "Entireimg")) %>%
  pivot_wider(names_from = Change, values_from = c(2:4)) %>%
  summarize(across(everything(), ~ .[!is.na(.)][1])) %>%
  rename_with(~ paste0("roi_", .), .cols = everything())

combined_tibble <- bind_cols(recinfo_data, calc_data, meanperf_data, roi_data)
return(combined_tibble)
}
